### ISSUE TITLE
Get ready for Hacktoberfest 2023

### ISSUE THREAD

**Issue by sheerlox** [kelektiv/node-cron#697]
![image](https://github.com/kelektiv/node-cron/assets/11234273/4c6c8a36-9057-4b90-ac18-fdaf92862ba7)

*Source: https://hacktoberfest.com/participation/#maintainers*

**Note: we need to release V3 before opening the repository to contributions to avoid merge hell between the `main` and `beta` branches.**

## TODO

- [x] release V3 (https://github.com/kelektiv/node-cron/pull/701)
- [x] Add a CONTRIBUTING.md file with contribution guidelines to your repository. (https://github.com/kelektiv/node-cron/issues/696)
- [X] Adopt a code of conduct to create a greater sense of inclusion and community for contributors. (https://github.com/kelektiv/node-cron/issues/696)
- [x] Add the `hacktoberfest` topic to your repository to opt-in to Hacktoberfest and indicate you’re looking for contributions.
- [x] Choose issues that have a well-defined scope and are self-contained.
- [x] Apply the `hacktoberfest` label to issues you want contributors to help with in your GitHub or GitLab project.

---

- [ ] Be ready to review pull/merge requests, accepting those that are valid by merging them, leaving an overall approving review, or by adding the `hacktoberfest-accepted` label.
- [ ] Reject any spammy requests you receive by labeling them as `spam`, and any other invalid contributions by closing them or labeling them as `invalid`.
